### ISSUE TITLE
win32 dll  [DllImport("helloword.dll")]

### ISSUE THREAD

**Issue by EnhWeb** [Fody/Home#433] opened 2022-03-20 09:45 UTC
win32 dll  [DllImport("helloword.dll")] OR [DllImport("helloword.so")]
helloword.dll OR helloword.so 能否也一起打包进单文件中？
helloword.dll OR helloword.so  Can they also be packaged into a single file?

**Comment by ltrzesniewski** [comment] 2022-03-20 11:38
Duplicate of https://github.com/Fody/Costura/issues/801

**Closed by ltrzesniewski** 2022-03-20 11:38 UTC
